name: clang-format
on:
  push:
  pull_request:
    branches: [ "master" ]
jobs:
    clang-format:
      uses: ./.github/workflows/clang-format.yaml
    run-tests:
      needs: clang-format
      uses: ./.github/workflows/run-tests.yaml