name: clang-format
on:
  push:
  pull_request:
    branches: [ "master" ]
jobs:
    call-workflow:
      uses: ./.github/workflows/clang-format.yaml
    call-workflow:
      uses: ./.github/workflows/run-tests.yaml