name: clang-format
on:
  push:
  pull_request:
    branches: [ "master" ]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '19'
          check-path: '.'
          fallback-style: 'Google'
