name: clang-format
on: [push]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    container: 
      image: silkeh/clang:18
      options: --user root
    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - name: Install deps
        run: apt update && apt install -y git 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run clang-format
        run: ./format_code.sh
      - name: Check
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          if [[ `git status --porcelain` ]]; then exit 1; fi