name: clang-format
on: [push]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '14'
          check-path: '.'
