name: run-tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: silkeh/clang:16
    steps:
      - name: Install git
        run: apt update && apt install -y git && apt install -y libgoogle-glog-dev && apt install -y libsnappy-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare for build
        run: mkdir $GITHUB_WORKSPACE/src/build
      - name: Index
         # https://github.com/actions/runner/issues/2058 have to write full path
        working-directory: /__w/LTest/LTest/src/build
        run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        working-directory: /__w/LTest/LTest/src/build
        run: cmake --build . --target lin_check_test -j
      - name: Run
        working-directory: /__w/LTest/LTest/src/build
        run: ./test/runtime/lin_check_test
  verifying-test:
    runs-on: ubuntu-latest
    container: 
      image: silkeh/clang:16
    steps:
      - name: Install git
        run: apt update && apt install -y git && apt install -y libgoogle-glog-dev && apt install -y libsnappy-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare for build
        run: mkdir $GITHUB_WORKSPACE/src/build
      - name: Index
        # https://github.com/actions/checkout/issues/841 have to write full path
        working-directory: /__w/LTest/LTest/src/build
        run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        working-directory: /__w/LTest/LTest/src/build
        run: cmake --build codegen -j
      - name: Install python packages
        run: apt install -y pip && pip3 install --break-system-packages click
      - name: Build nonlinear_queue
        working-directory: /__w/LTest/LTest/src/verifying
        run: ./verify.py build -g --src ./targets/nonlinear_queue.cpp
      - name: Check pct strategy
        working-directory: /__w/LTest/LTest/src/verifying
        run: if [[ "$(./verify.py run --strategy pct --tasks 10 --rounds 240)" =~ .*"success".* ]]; then exit 1; fi;
