name: run-tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: 
      image: silkeh/clang:18
      options: --user root
    steps:
      - name: Install deps
        run: apt update && apt install -y git ninja-build valgrind
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Index
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --target lin_check_test
      - name: Run 
        run: ./build/test/runtime/lin_check_test
  verifying-test-lock-free-queue:
    runs-on: ubuntu-latest
    container: 
      image: silkeh/clang:18
      options: --user root
    steps:
      - name: Install deps
        run: |
          apt update && apt install -y git ninja-build valgrind libgoogle-glog-dev libsnappy-dev protobuf-compiler pip
          pip3 install --break-system-packages click
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Index
        run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
      - name: Run nonlinear_queue with pct
        run: if [[ "$(./verifying/verify.py run -g nonlinear_queue --strategy pct --tasks 10 --rounds 240)" =~ .*"success".* ]]; then exit 1; fi;